import React, { useState, useEffect } from 'react';
import { X, Save, Loader2, AlertCircle, Package, Calendar, PlusCircle } from 'lucide-react';
import { formatDate } from '../../utils/formatters';

export const DEFECT_MODAL_INITIAL_STATE = { checkDate: '', barcodeDate: '', vendor: '', defectContent: '', cost: 0, productName: '', color: '', size: '', quantity: 1, source: 'ER', releaseDate: '', repairDate: '', deductionDate: '', returnDate: '', hubDate: '', manager: '', note: '' };

export const DefectModal = ({ isOpen, onClose, onSave, initialData, isSaving, loggedInUser }) => {
  const getInitialFormState = () => ({ ...DEFECT_MODAL_INITIAL_STATE, checkDate: new Date().toISOString().split('T')[0] });
  const [formData, setFormData] = useState(getInitialFormState);
  useEffect(() => {
    if (initialData) setFormData(initialData);
    else setFormData({ ...getInitialFormState(), manager: loggedInUser?.name || '' });
  }, [initialData, isOpen, loggedInUser]);
  const handleChange = (e) => { const { name, value } = e.target; setFormData(prev => ({ ...prev, [name]: value })); };
  const handleSubmit = (e) => { e.preventDefault(); onSave(formData, false); };
  const handleSaveAndContinue = async () => { if (!formData.checkDate || !formData.vendor) { alert("필수 항목(불량확인일, 업체명)을 입력해주세요."); return; } const success = await onSave(formData, true); if (success) setFormData({ ...getInitialFormState(), manager: loggedInUser?.name || '' }); };
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-stone-900/60 backdrop-blur-sm flex items-center justify-center z-[70] p-4 animate-in fade-in duration-200">
      <div className="bg-white shadow-2xl w-full max-w-4xl max-h-[90vh] overflow-y-auto transform transition-all scale-100 border-t-4 border-stone-800 rounded-none">
        <div className="px-8 py-6 border-b border-stone-100 flex justify-between items-center sticky top-0 bg-white/95 backdrop-blur-md z-10"><h2 className="text-2xl font-extrabold text-stone-900 tracking-tight">{initialData ? '불량 내역 수정' : '새 불량 등록'}</h2><button onClick={onClose} className="text-stone-400 hover:text-stone-900 bg-stone-50 hover:bg-stone-200 p-2 transition-colors rounded-sm"><X size={24} strokeWidth={2.5} /></button></div>
        <form onSubmit={handleSubmit} className="p-8 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 bg-stone-50/30">
          <div className="col-span-full pb-3 border-b border-stone-200"><h3 className="text-sm font-black text-stone-700 flex items-center gap-2 uppercase tracking-widest"><AlertCircle size={18} strokeWidth={2.5} /> 기본 정보</h3></div>
          <div className="space-y-1.5"><label className="text-xs font-bold text-stone-600 uppercase tracking-wide">불량확인일 <span className="text-red-500">*</span></label><input required type="date" name="checkDate" value={formData.checkDate} onChange={handleChange} className="w-full px-4 py-3 bg-white border border-stone-300 text-sm focus:ring-2 focus:ring-stone-900 focus:border-stone-900 outline-none transition-all font-medium rounded-sm" /></div>
          <div className="space-y-1.5"><label className="text-xs font-bold text-stone-600 uppercase tracking-wide">바코드 날짜</label><input type="text" name="barcodeDate" value={formData.barcodeDate} onChange={handleChange} placeholder="YYYY-MM-DD or X" className="w-full px-4 py-3 bg-white border border-stone-300 text-sm focus:ring-2 focus:ring-stone-900 focus:border-stone-900 outline-none transition-all font-medium rounded-sm" /></div>
          <div className="space-y-1.5"><label className="text-xs font-bold text-stone-600 uppercase tracking-wide">업체명 <span className="text-red-500">*</span></label><input required type="text" name="vendor" value={formData.vendor} onChange={handleChange} className="w-full px-4 py-3 bg-white border border-stone-300 text-sm focus:ring-2 focus:ring-stone-900 focus:border-stone-900 outline-none transition-all font-medium rounded-sm" /></div>
          <div className="col-span-full mt-6 pb-3 border-b border-stone-200"><h3 className="text-sm font-black text-stone-700 flex items-center gap-2 uppercase tracking-widest"><Package size={18} strokeWidth={2.5} /> 상품 정보</h3></div>
          <div className="space-y-1.5 col-span-2"><label className="text-xs font-bold text-stone-600 uppercase tracking-wide">상품명</label><input type="text" name="productName" value={formData.productName} onChange={handleChange} className="w-full px-4 py-3 bg-white border border-stone-300 text-sm focus:ring-2 focus:ring-stone-900 focus:border-stone-900 outline-none transition-all font-medium rounded-sm" /></div>
          <div className="space-y-1.5"><label className="text-xs font-bold text-stone-600 uppercase tracking-wide">제품원가</label><input type="number" name="cost" value={formData.cost} onChange={handleChange} className="w-full px-4 py-3 bg-white border border-stone-300 text-sm focus:ring-2 focus:ring-stone-900 focus:border-stone-900 outline-none transition-all font-mono font-medium rounded-sm" /></div>
          <div className="space-y-1.5"><label className="text-xs font-bold text-stone-600 uppercase tracking-wide">색상</label><input type="text" name="color" value={formData.color} onChange={handleChange} className="w-full px-4 py-3 bg-white border border-stone-300 text-sm focus:ring-2 focus:ring-stone-900 focus:border-stone-900 outline-none transition-all font-medium rounded-sm" /></div>
          <div className="space-y-1.5"><label className="text-xs font-bold text-stone-600 uppercase tracking-wide">사이즈</label><input type="text" name="size" value={formData.size} onChange={handleChange} className="w-full px-4 py-3 bg-white border border-stone-300 text-sm focus:ring-2 focus:ring-stone-900 focus:border-stone-900 outline-none transition-all font-medium rounded-sm" /></div>
          <div className="space-y-1.5"><label className="text-xs font-bold text-stone-600 uppercase tracking-wide">수량</label><input type="number" name="quantity" value={formData.quantity} onChange={handleChange} className="w-full px-4 py-3 bg-white border border-stone-300 text-sm focus:ring-2 focus:ring-stone-900 focus:border-slate-900 outline-none transition-all font-bold text-center rounded-sm" /></div>
          <div className="col-span-full mt-6 pb-3 border-b border-stone-200"><h3 className="text-sm font-black text-stone-700 flex items-center gap-2 uppercase tracking-widest"><AlertCircle size={18} strokeWidth={2.5} /> 불량 상세</h3></div>
          <div className="col-span-2 space-y-1.5"><label className="text-xs font-bold text-stone-600 uppercase tracking-wide">불량내용</label><input type="text" name="defectContent" value={formData.defectContent} onChange={handleChange} className="w-full px-4 py-3 bg-white border border-stone-300 text-sm focus:ring-2 focus:ring-stone-900 focus:border-stone-900 outline-none transition-all font-medium rounded-sm" /></div>
          <div className="space-y-1.5"><label className="text-xs font-bold text-stone-600 uppercase tracking-wide">불량출처</label><select name="source" value={formData.source} onChange={handleChange} className="w-full px-4 py-3 bg-white border border-stone-300 text-sm focus:ring-2 focus:ring-stone-900 focus:border-stone-900 outline-none transition-all cursor-pointer font-bold text-stone-700 rounded-sm"><option value="ER">ER</option><option value="반품">반품</option><option value="매장">매장</option></select></div>
          <div className="col-span-full mt-6 pb-3 border-b border-stone-200"><h3 className="text-sm font-black text-stone-700 flex items-center gap-2 uppercase tracking-widest"><Calendar size={18} strokeWidth={2.5} /> 처리 일정 (경리/허브)</h3></div>
          <div className="space-y-1.5"><label className="text-xs font-bold text-stone-600 uppercase tracking-wide">불량출고일</label><input type="date" name="releaseDate" value={formData.releaseDate} onChange={handleChange} className="w-full px-4 py-3 bg-white border border-stone-300 text-sm focus:ring-2 focus:ring-stone-900 focus:border-stone-900 outline-none transition-all font-mono rounded-sm" /></div>
          <div className="space-y-1.5"><label className="text-xs font-bold text-stone-600 uppercase tracking-wide">수선확인일</label><input type="date" name="repairDate" value={formData.repairDate} onChange={handleChange} className="w-full px-4 py-3 bg-white border border-stone-300 text-sm focus:ring-2 focus:ring-stone-900 focus:border-stone-900 outline-none transition-all font-mono rounded-sm" /></div>
          <div className="space-y-1.5"><label className="text-xs font-bold text-stone-600 uppercase tracking-wide">차감 적용일</label><input type="date" name="deductionDate" value={formData.deductionDate} onChange={handleChange} className="w-full px-4 py-3 bg-white border border-stone-300 text-sm focus:ring-2 focus:ring-stone-900 focus:border-stone-900 outline-none transition-all font-mono rounded-sm" /></div>
          <div className="space-y-1.5"><label className="text-xs font-bold text-stone-600 uppercase tracking-wide">반환 적용일</label><input type="date" name="returnDate" value={formData.returnDate} onChange={handleChange} className="w-full px-4 py-3 bg-white border border-stone-300 text-sm focus:ring-2 focus:ring-stone-900 focus:border-stone-900 outline-none transition-all font-mono rounded-sm" /></div>
          <div className="space-y-1.5"><label className="text-xs font-bold text-stone-600 uppercase tracking-wide">허브 출고일</label><input type="date" name="hubDate" value={formData.hubDate} onChange={handleChange} className="w-full px-4 py-3 bg-white border border-stone-300 text-sm focus:ring-2 focus:ring-stone-900 focus:border-stone-900 outline-none transition-all font-mono rounded-sm" /></div>
          <div className="space-y-1.5"><label className="text-xs font-bold text-stone-600 uppercase tracking-wide">담당자</label><input type="text" name="manager" value={formData.manager} onChange={handleChange} className="w-full px-4 py-3 bg-white border border-stone-300 text-sm focus:ring-2 focus:ring-stone-900 focus:border-stone-900 outline-none transition-all rounded-sm" placeholder="담당자 이름" /></div>
          <div className="space-y-1.5 col-span-full"><label className="text-xs font-bold text-stone-600 uppercase tracking-wide">비고</label><textarea name="note" value={formData.note} onChange={handleChange} className="w-full px-4 py-3 bg-white border border-stone-300 rounded-none text-sm focus:ring-2 focus:ring-stone-900 focus:border-stone-900 outline-none transition-all h-24 resize-none" placeholder="특이사항 입력" /></div>
          <div className="col-span-full flex justify-end gap-3 mt-4 pt-6 border-t border-stone-200">
            <button type="button" onClick={onClose} disabled={isSaving} className="px-5 py-3 text-stone-600 hover:bg-white hover:text-stone-900 border border-transparent hover:border-stone-300 text-sm font-bold transition-all disabled:opacity-50 rounded-sm">취소</button>
            {!initialData && (<button type="button" onClick={handleSaveAndContinue} disabled={isSaving} className="px-5 py-3 bg-stone-100 text-stone-700 hover:bg-stone-200 hover:text-stone-900 border border-stone-200 text-sm font-bold transition-all rounded-sm flex items-center gap-2 disabled:opacity-50">{isSaving ? <Loader2 className="animate-spin h-4 w-4" /> : <PlusCircle size={16} />}저장 후 계속 추가</button>)}
            <button type="submit" disabled={isSaving} className="px-8 py-3 bg-stone-800 text-white hover:bg-stone-700 text-sm font-bold transition-all shadow-md shadow-stone-200 flex items-center gap-2 disabled:opacity-70 disabled:shadow-none active:scale-[0.98] rounded-sm">{isSaving && <Loader2 className="animate-spin h-4 w-4" />}{isSaving ? '저장 중...' : (initialData ? '수정 완료' : '저장하기')}</button>
          </div>
        </form>
      </div>
    </div>
  );
};
